# ----------------------------------------------------------------------------------------------
# |                         BuildTeamTools - by BuildTheEarth
# ----------------------------------------------------------------------------------------------
# | [Github Repo]           https://github.com/BuildTheEarth/BuildTeamTools
# | [Config Documentation]  https://resources.buildtheearth.net/doc/configuration-tpEHSZ6Zt2#h-general-configuration
# | [Contacts - Discord]    BTE Development Hub, @zoriot
# ----------------------------------------------------------------------------------------------

# The Build Team API Key used to fetch build team info for display.
# Visit https://resources.buildtheearth.net/s/btt/doc/configuration-tpEHSZ6Zt2#h-api-key-of-the-server
# for an up-to-date guide on how to get your own API key.
api-key: 00000000-0000-0000-0000-000000000000

# The main world using the custom BTE Dynmaxion projection
earth-world: world

# The modules that should be disabled
disabled-modules:
  #- "module-name"

# Enable or disable the debug mode
debug: false

# NOTE: Do not change
config-version: 1.4