# ----------------------------------------------------------------------------------------------
# |                         BuildTeamTools - by BuildTheEarth
# ----------------------------------------------------------------------------------------------
# | [Github Repo]           https://github.com/BuildTheEarth/BuildTeamTools
# | [Config Documentation]  https://resources.buildtheearth.net/doc/configuration-tpEHSZ6Zt2#h-general-configuration
# | [Contacts - Discord]    BTE Development Hub, @zoriot
# ----------------------------------------------------------------------------------------------

# The Build Team API Key used to fetch build team info for display. Find the key on the Minecraft Network at "buildtheearth.net".
# Navigate: Compass > Build Teams > Your Country > Your Team → Edit > API-Key → Right click on it → Click on the api key in chat.
# Without this key, some plugin components won`t function. For assistance, see #server-support on the staff discord -
# you might need to be added as a owner first.
api-key: 00000000-0000-0000-0000-000000000000

# The main world using the custom BTE Dynmaxion projection
earth-world: world

# The modules that should be disabled
disabled-modules:
  #- "module-name"

# Enable or disable the debug mode
debug: false

# NOTE: Do not change
config-version: 1.4